publicSide:
  tcp:
    - publicSidePort: 20000
      tunnelProtocolClass: th.in.meen.natmeout.tunneler.tcp.PublicSideTunnelerImpl
      tunnelProtocolConfig:
        secret: 'ThisIsS3ret'
        tunnelPort: 5000
  ## UDP will be supported later

natSide:
  tcp: 
    - natSideDestinationHost: www.meen.in.th
      natSideDestinationPort: 22
      tunnelProtocolClass: th.in.meen.natmeout.tunneler.tcp.NatSideTunnelerImpl
      tunnelProtocolConfig:
        secret: 'ThisIsS3ret'
        tunnelHost: 127.0.0.1
        tunnelPort: 5000